version: "3.9"
services:
  postgres:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: "demo"
      POSTGRES_PASSWORD: "demo"
    volumes:
      - postgres-example:/var/lib/postgresql/data
    ports:
      - "5432:5432"