version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "tms_demo"
      POSTGRES_USER: "tmsuser"
      POSTGRES_PASSWORD: "tmspassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U tmsuser -d tms_demo
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-tms:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-tms:
  pgadmin-data: